"""
Các bộ từ điển dùng cho preprocessing.
Tách riêng khỏi preprocessing.py để file xử lý chính gọn hơn.
"""

SLANG_DICT_RAW = {
    # Nhóm từ tục / xúc phạm trực tiếp
    "dell":    "đếch",
    "đell":    "đếch",
    "đéo":     "đếch",
    "deo":     "đếch",
    "eo":      "éo",
    "đm":      "địt_mẹ",
    "dm":      "địt_mẹ",
    "đmm":     "địt_mẹ_mày",
    "dmm":     "địt_mẹ_mày",
    "dcm":     "địt_cụ_mày",
    "cc":      "cục_cứt",
    "cl":      "cái_lồn",
    "clm":     "cái_lồn_má",
    "clgv":    "cái_lồn_gì_vậy",
    "clgt":    "cái_lồn_gì_thế",
    "clg":     "cái_lồn_gì",
    "lol":     "lồn",
    "loz":     "lồn",
    "lz":      "lồn",
    "l":       "lồn",
    "ml":      "mặt_lồn",
    "cmm":     "con_mẹ_mày",
    "cmn":     "con_mẹ_nó",
    "cmnr":    "con_mẹ_nó_rồi",
    "xamlol":  "xàm_lồn",
    "xamlone": "xàm_lồn",
    "sml":     "sấp_mặt_lồn",
    "vl":      "vãi_lồn",
    "vcl":     "vãi_cả_lồn",
    "vkl":     "vãi_cả_lồn",
    "vll":     "vãi_lồn_luôn",
    "vlon":    "vãi_lồn",
    "vailon":  "vãi_lồn",
    "vcđ":     "vãi_cả_đái",
    "cđ":      "con_đĩ",
    "đjs":     "địt_mẹ",
    "dhs":     "đéo_hiểu_sao",
    "xl":      "xạo_lồn",
    "éo":      "đéo",
    "đ":       "đéo",
    "đesss":   "đéo",
    "moẹ":     "mẹ",

    # Nhóm biến âm cố tình (teencode âm thanh)
    "thỳ":     "thì",
    "dề":      "về",
    "ge":      "ghê",
    "thik":    "thích",
    "ik":      "đi",
    "jeenh":   "kênh",
    "zời":     "trời",
    "zị":      "vậy",
    "zay":     "vậy",
    "ưiiiii":  "ơi",
    "qá":      "quá",
    "qa":      "quá",
    "roày":    "rồi",
    "jui":     "rồi",
    "ni":      "này",
    "nà":      "này",
    "lun":     "luôn",
    "ah":      "à",
    "kkk":     "haha",
    "khong":   "không",
    "khongg":  "không",
    "khonggg": "không",
    # Bổ sung: Lóng chửi bới / Teencode ẩn dụ
    "coin_card": "con_cặc",
    "concard": "con_cặc",
    "cái_lồn_què": "cái_lồn",

    # Bổ sung: Từ vựng mỉa mai Gen Z
    "cảm_lạnh": "tồi_tệ",
    "báo": "phá_hoại",
    "xu_cà_na": "xui_xẻo",
    "chằm_zn": "trầm_cảm",
    "luật_hoa_quả": "luật_nhân_quả",
    "ô_dề": "lố_lăng",
    "bất_ổn": "bất_ổn",
    "thăm_ngàn": "làm_việc_khổ_sai",
    "ra_chuồng_gà": "tệ_hại",
}

ABBREV_DICT_RAW = {
    # Phủ định
    "ko":    "không",
    "k":     "không",
    "hk":    "không",
    "hok":   "không",
    "kg":    "không",

    # Đại từ / xưng hô
    "m":     "mày",
    "t":     "tao",
    "e":     "em",
    "tui":   "tôi",
    "mk":    "mình",
    "ck":    "chồng",
    "vk":    "vợ",
    "b":     "bạn",
    "a":     "anh",

    # Động từ / trạng từ
    "dc":    "được",
    "đc":    "được",
    "vs":    "với",
    "v":     "vậy",
    "r":     "rồi",
    "j":     "gì",
    "z":     "vậy",
    "lm":    "làm",
    "ok":    "được_rồi",
    "iu":    "yêu",
    "ak":    "à",
    "cx":    "cũng",
    "bit":   "biết",
    "ht":    "hết",
    "nc":    "nói_chuyện",
    "trc":   "trước",
    "tr":    "trước",
    "nhe":   "nhé",
    "roi":   "rồi",
    "gi":    "gì",
    "luon":  "luôn",
    "dg":    "đang",

    # Viết tắt không dấu — từ ngữ thông thường
    "nguoi": "người",
    "vn":    "việt_nam",

    # Mạng xã hội / internet
    "mn":    "mọi_người",
    "mng":   "mọi_người",
    "ae":    "anh_em",
    "ac":    "anh_chị",
    "ad":    "admin",
    "fb":    "facebook",
    "ib":    "nhắn_tin",
    "inb":   "nhắn_tin",
    "rep":   "trả_lời",
    "cmt":   "bình_luận",
    "stt":   "trạng_thái",
    "tus":   "trạng_thái",
    "wed":   "web",

    # Viết tắt thông dụng khác
    "ny":    "người_yêu",
    "bh":    "bao_giờ",
    "hqua":  "hôm_qua",
    "hqa":   "hôm_qua",
    "ntn":   "như_thế_nào",
    "bt":    "bình_thường",
    "bth":   "bình_thường",
    "bn":    "bạn",
    "qtrong":"quan trọng",
    "tgian": "thời_gian",
    "ng":    "người",
    "ngta":  "người_ta",
    "đg":    "đang",
    "trk":   "trước",
    "h":     "giờ",
    "kp":    "không_phải",
    "in4":   "thông_tin",
    "sud":   "đăng_ký",
    "cacban":"các bạn",
    "dlv":   "dư_luận_viên",
    "hvb":   "hồng_vệ_binh",
    "3":     "ba",
    "bnhiu":  "bao_nhiêu",
    "ddi":   "đi",
}

COMPOUND_DICT_RAW = {
    "nhà nước": "nhà_nước",
    "chính phủ": "chính_phủ",
    "quốc gia": "quốc_gia",
    "nhân dân": "nhân_dân",
    "dư luận viên": "dư_luận_viên",
    "nhà báo": "nhà_báo",
    "báo công an": "báo_công_an",
    "bộ đội": "bộ_đội",
    "công an": "công_an",
    "cách ly": "cách_ly",
    "khâu trang": "khẩu_trang",
    "khẩu trang": "khẩu_trang",
    "táo quân": "táo_quân",
    "năm mới": "năm_mới",
    "chúc mừng": "chúc_mừng",
    "mừng năm mới": "mừng_năm_mới",
    "năm nay": "năm_nay",
    "năm sau": "năm_sau",
    "hôm nay": "hôm_nay",
    "hôm qua": "hôm_qua",
    "bây giờ": "bây_giờ",
    "lần đầu": "lần_đầu",
    "cuối cùng": "cuối_cùng",
    "ngày càng": "ngày_càng",
    "nói chung": "nói_chung",
    "thật sự": "thật_sự",
    "rất thuyết phục": "rất_thuyết_phục",
    "cực kỳ": "cực_kỳ",
    "cực kì": "cực_kì",
    "hợp lý": "hợp_lý",
    "tuyệt vời": "tuyệt_vời",
    "chắc chắn": "chắc_chắn",
    "không biết": "không_biết",
    "không phải": "không_phải",
    "không cần": "không_cần",
    "không có": "không_có",
    "chỉ có": "chỉ_có",
    "có vẻ": "có_vẻ",
    "được rồi": "được_rồi",
    "làm sao": "làm_sao",
    "như thế": "như_thế",
    "thế nào": "thế_nào",
    "bao giờ": "bao_giờ",
    "xin lỗi": "xin_lỗi",
    "xin phép": "xin_phép",
    "xin video": "xin_video",
    "xin link": "xin_link",
    "nghe nói": "nghe_nói",
    "xem video": "xem_video",
    "link video": "link_video",
    "nhắn tin": "nhắn_tin",
    "trả lời": "trả_lời",
    "bình luận": "bình_luận",
    "đăng ký": "đăng_ký",
    "bình thường": "bình_thường",
    "thời gian": "thời_gian",
    "thành công": "thành_công",
    "công nhận": "công_nhận",
    "phát triển": "phát_triển",
    "quảng cáo": "quảng_cáo",
    "gia đình": "gia_đình",
    "nước ngoài": "nước_ngoài",
    "người dân": "người_dân",
    "nhiều người": "nhiều_người",
    "mấy thằng": "mấy_thằng",
    "mấy đứa": "mấy_đứa",
    "lãnh đạo": "lãnh_đạo",
    "chính quyền": "chính_quyền",
    "chương trình": "chương_trình",
    "câu chuyện": "câu_chuyện",
    "bản thân": "bản_thân",
    "quan tâm": "quan_tâm",
    "suy nghĩ": "suy_nghĩ",
    "cẩn thận": "cẩn_thận",
    "quan trọng": "quan_trọng",
    "khẩu nghiệp": "khẩu_nghiệp",
    "cộng đồng": "cộng_đồng",
    "cộng sản": "cộng_sản",
    "phản động": "phản_động",
    "tham nhũng": "tham_nhũng",
    "trẻ trâu": "trẻ_trâu",
    "huyền thoại": "huyền_thoại",
    "danh hài": "danh_hài",
    "giải trí": "giải_trí",
    "cuộc sống": "cuộc_sống",
    "sức khỏe": "sức_khỏe",
    "mùa dịch": "mùa_dịch",
    "dịch bệnh": "dịch_bệnh",
    "tình hình": "tình_hình",
    "tương lai": "tương_lai",
    "may mắn": "may_mắn",
    "yên tâm": "yên_tâm",
    "đạo đức": "đạo_đức",
    "giao thông": "giao_thông",
    "hình ảnh": "hình_ảnh",
    "cảm giác": "cảm_giác",
    "khả năng": "khả_năng",
    "thần kinh": "thần_kinh",
    "phong cách": "phong_cách",
    "câu nói": "câu_nói",
    "hợp tác": "hợp_tác",
    "ngày xưa": "ngày_xưa",
    "nước mắt": "nước_mắt",
    "người việt": "người_việt",
    "sài gòn": "sài_gòn",
    "sân bay": "sân_bay",
    "máy bay": "máy_bay",
    "fan cứng": "fan_cứng",
    "xạo lồn": "xạo_lồn",
    "tấu hài": "tấu_hài",
    "cánh hoa": "cánh_hoa",
    "vàng ngọc": "vàng_ngọc",
    "cao lãnh": "cao_lãnh",
    "trung thu": "trung_thu",
    "trả nợ": "trả_nợ",
    "không gian": "không_gian",
    "thể hiện": "thể_hiện",
    "sản phẩm": "sản_phẩm",
    "người khác": "người_khác",
    "nói chuyện": "nói_chuyện",
    "xin chào": "xin_chào",
    "về việt nam": "về_việt_nam",
    "trên mạng": "trên_mạng",
    "chụp ảnh": "chụp_ảnh",
    "làm việc": "làm_việc",
    "đi học": "đi_học",
    "đi làm": "đi_làm",
    "đọc báo": "đọc_báo",
    "xem phim": "xem_phim",
    "chốt đơn": "chốt_đơn",
    "like dạo": "like_dạo",
    "bị chặn": "bị_chặn",
    "bảo vệ": "bảo_vệ",
    "kiểm soát": "kiểm_soát",
    "thuyết phục": "thuyết_phục",
    "hợp nhóm": "hợp_nhóm",
    "công khai": "công_khai",
    "bị phạt": "bị_phạt",
    "quá hay": "quá_hay",
    "quá đẹp": "quá_đẹp",
    "quá tốt": "quá_tốt",
    "bao nhiêu": "bao_nhiêu",
    "xét nghiệm": "xét_nghiệm",
    "văn hóa": "văn_hóa",
    "văn hoá": "văn_hoá",
    "đồng chí": "đồng_chí",
    "nước hoa": "nước_hoa",
    "chủ tịch": "chủ_tịch",
    "kinh nghiệm": "kinh_nghiệm",
    "nổi tiếng": "nổi_tiếng",
    "thanh niên": "thanh_niên",
    "phân biệt": "phân_biệt",
    "đồng lòng": "đồng_lòng",
    "bỏ phiếu": "bỏ_phiếu",
    "bán hàng": "bán_hàng",
    "chụp hình": "chụp_hình",
    "việt nam": "việt_nam",
    "đất nước": "đất_nước",
    "virus corona": "virus_corona",
    "covid 19": "covid_19"
}

# ==========================================
# STOPWORDS
# ==========================================
STOPWORDS = set([
    "và", "là", "như", "thì", "mà", "nếu", "có", "các", "những", "của",
    "cho", "đi", "cái", "nó", "rồi", "lại", "ra", "còn",
    "phải", "mình", "ơi", "nào", "thế", "sao", "ai", "ở", "đâu", "đó",
    "để", "thôi", "vậy", "với", "chỉ", "cả", "đã", "vào", "nên", "nữa",
    "từ", "khi", "đến", "trong", "vì", "cứ", "sau", "gì", "rất",
    "quá", "đang", "mới", "hơn", "luôn", "hoặc", "làm",
    "thấy", "bị", "nhé", "nha", "hả", "thật",
    "cũng",  "biết",  "muốn",
    "vẫn",   "cần", "chứ",
    "sẽ",    "đây",
    "đấy",   "lắm",   "hết",   "theo",  "nhau",
    "vừa",   "thêm",  "tất",
])